with SALE_SUM as(
select PRODUCT_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
FROM OFFLINE_SALE 
GROUP BY PRODUCT_ID
)

SELECT PRODUCT_CODE, (P.PRICE * SALES_AMOUNT) SALES
FROM PRODUCT P INNER join SALE_SUM SS ON p.PRODUCT_ID = SS.PRODUCT_ID
order by SALES desc, PRODUCT_CODE asc;
