SELECT UGB.TITLE TITLE,UGB.BOARD_ID BOARD_ID,UGR.REPLY_ID ,UGR.WRITER_ID WRITER_ID,UGR.CONTENTS CONTENTS, date_format(UGR.CREATED_DATE,'%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD as UGB inner JOIN USED_GOODS_REPLY as UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE LIKE '2022-10%'
order by CREATED_DATE asc, TITLE asc