WITH UNAVAILABLE_CAR AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
),
CAR_DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE IN ('세단', 'SUV') 
      AND DURATION_TYPE = '30일 이상'
)

SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    -- 30일 대여료 계산 (DAILY_FEE * 30 * (1 - 할인율/100))
    FLOOR(C.DAILY_FEE * 30 * (1 - CD.DISCOUNT_RATE / 100.0)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_DISCOUNT CD ON C.CAR_TYPE = CD.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID FROM UNAVAILABLE_CAR) -- 대여 불가능한 차량 제외
  AND C.CAR_TYPE IN ('세단', 'SUV')
HAVING FEE >= 500000 AND FEE < 2000000 
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;