SELECT ROUTE ,concat(round(SUM(D_BETWEEN_DIST),1),'km')  TOTAL_DISTANCE, concat(round(AVG(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE
order by SUM(D_BETWEEN_DIST) desc