WITH USER_2021 AS (
    SELECT 
        USER_ID,
        COUNT(*) OVER() AS TOTAL_USERS 
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT 
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / MAX(U.TOTAL_USERS), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE OS
JOIN USER_2021 U ON OS.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;