-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(UGB.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD UGB left join USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
where UGB.STATUS = 'DONE'
GROUP BY UGB.WRITER_ID
having TOTAL_SALES >= 700000
order by TOTAL_SALES asc;