with APPOINTMENTCheck as(
select APNT_NO, APNT_YMD, PT_NO, MCDP_CD,MDDR_ID
FROM APPOINTMENT
WHERE APNT_CNCL_YN = "N" and APNT_YMD LIKE '2022-04-13%' and MCDP_CD = 'CS'
)




SELECT APNT_NO,	PT_NAME,	AC.PT_NO,	AC.MCDP_CD,	DR_NAME,	APNT_YMD
FROM APPOINTMENTCheck AC left join DOCTOR D ON AC.MDDR_ID = D.DR_ID
left join PATIENT P ON AC.PT_NO = P.PT_NO
order by APNT_YMD asc;