SELECT ID, FISH_NAME, LENGTH
from
    (SELECT 
    B.FISH_NAME, 
    A.ID, 
    A.LENGTH,
    RANK() OVER (PARTITION BY A.FISH_TYPE ORDER BY A.LENGTH DESC) AS fish_RANK
FROM 
    FISH_INFO A 
JOIN 
    FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY 
    B.FISH_NAME, FISH_RANK) AS RANKED_FISH
    where fish_RANK = 1
    order by ID ASC;