with ten_rent as(
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-10-01' and '2022-10-31'
)


SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC INNER JOIN  ten_rent TR USING (CAR_ID)
WHERE CAR_TYPE = '세단'
order by CAR_ID desc;